---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: silverwater
# description will be included in the image's metadata
description: a very funny linux image for myself and myself only <3

# Project Bluefin latest
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - from-file: rpm-ostree.yml
  - from-file: dnf.yml
  - from-file: fonts.yml
  - from-file: default-flatpaks.yml
  - from-file: gnome-extensions.yml
  - from-file: os-release.yml
